double Tan(double x);
double Sin(double x);
double Cos(double x);
double 절대값(double x);
double 지수값(double x);
double n(double x);
void Log(double x);
void PI(double);
void INT(double x);
void HEX(double x);
void OCT(double x);
void BINARY(double x);
void as(double x);
void ac(double x);
void at(double x);
void sh(double x);
void ch(double x);
void th(double x);